### ISSUE TITLE
왜그랫대.....? ㅋㅋㅋㅋ

### ISSUE THREAD

**Issue by gomjellie** [unemployed-union/synology_flask_wiki#1]

**Comment by unemployed-union** [comment]
일반적이라면 어떻게든 끌어와서 쓸 수 있는데 얘는 처음 만져봐서 그런가 방법이 다 안먹어요 ㅋㅋㅋㅋ....
모듈 없다고 떠서 또 깔려고 하면 또 오류나는데 고치는 방법은 또 시놀로지 기준에서 존재하지 않는 디렉터리나 파일을 찾고...어...음...

**Comment by gomjellie** [comment]
ssh로 접속하는거 해봣지?
ssh로 접속해보니까 curl, git 같은것도 안깔린 리눅스던데

**Comment by unemployed-union** [comment]
계속 ssh로 작업중이에요!
SQL 관련 문제는 이미 처리한 문제라서...제 해결방안 적고 있어요.
